kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ese
  name: ese-deployment-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]