kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
- namespace: ese
  name: ese-service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
